runtime: python310
entrypoint: gunicorn -b :$PORT ai_tools_platform.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "ai_tools_platform.settings"
  SECRET_KEY: "your-secret-key"
  DEBUG: "False"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
