# Generated by Django 5.2 on 2025-04-17 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('structure_feedback', models.TextField(blank=True, null=True)),
                ('content_feedback', models.TextField(blank=True, null=True)),
                ('skills_feedback', models.TextField(blank=True, null=True)),
                ('experience_feedback', models.TextField(blank=True, null=True)),
                ('improvement_suggestions', models.TextField(blank=True, null=True)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cv_documents/')),
                ('content_text', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='cv_reviewer.cvreview')),
            ],
        ),
    ]
